name: bdix_ftp_tester
description: "A modern BDIX FTP link tester application"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  window_manager: ^0.3.7
  path_provider: ^2.1.1
  flutter_markdown: ^0.6.18
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  card_swiper: ^3.0.1
  blur: ^3.1.0
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"
  remove_alpha_ios: true 